server:
  port: 9999
spring:
  application:
    name: weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/George970206/micro-service
          search-paths: config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/