spring:
  application:
    name: weather-eureka-client-zuul
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/

zuul:
  routes:
    city:
      path: /city/**
      serviceId: weather-city-eureka
    data:
      path: /data/**
      serviceId: weather-data-eureka
