
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  application:
    name: weather-data-eureka
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
